package com.unsubscribeos.core.mail;

import java.util.Map;
import java.util.Set;

/**
 * Heuristic for telling automated / list mail apart from personal correspondence, using the
 * standard headers bulk senders set (and humans don't). Mail you'd want to clean up — newsletters,
 * notifications, promotions, receipts — carries at least one of these; a personal email you wrote,
 * or a reply someone sent you, carries none. Lets the dashboard surface bulk senders for deletion
 * while keeping personal mail out of reach of the bulk-delete button.
 */
public final class BulkMail {

    private static final Set<String> BULK_PRECEDENCE = Set.of("bulk", "list", "junk");

    private BulkMail() {}

    /** True if any list/automation header marks this message as non-personal. Keys must be lower-case. */
    public static boolean isBulk(Map<String, String> headers) {
        return present(headers, "list-unsubscribe")
                || present(headers, "list-id")
                || present(headers, "list-post")
                || BULK_PRECEDENCE.contains(value(headers, "precedence"))
                || autoSubmitted(headers);
    }

    private static boolean present(Map<String, String> headers, String key) {
        String value = headers.get(key);
        return value != null && !value.isBlank();
    }

    private static String value(Map<String, String> headers, String key) {
        String value = headers.get(key);
        return value == null ? "" : value.trim().toLowerCase();
    }

    /** RFC 3834: anything other than "no" means the message was generated by a machine. */
    private static boolean autoSubmitted(Map<String, String> headers) {
        String value = value(headers, "auto-submitted");
        return !value.isEmpty() && !value.equals("no");
    }
}
